### ISSUE TITLE
Образцы конфигов

### ISSUE THREAD

**Issue by chip7777** [Limych/ha-narodmon#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chip7777** [comment]
Добрый день! Не смог найти образцы конфига дополнения. Хочу опубликовать датчик уличной температуры.

**Comment by Limych** [comment]
Компонент пока только для получения данных, не для публикации.
