### ISSUE TITLE
публикация значения датчиков Т на улице и атмосферного давления

### ISSUE THREAD

**Issue by YDenis1978** [Limych/ha-narodmon#118]
Здравствуйте.
Подскажите пожалуйста. Я ранее использовал сервер умного дома MajorDomo - публиковал в narodmon значения уличного датчика температуры и давления. Сейчас использую Home assistant. Не могу разобраться, возможно ли с установленной интеграцией narodmon публиковать значения датчиков Т на улице и атмосферного давления?

благодарю

**Comment by Limych** [comment]
Дубликат. #109
