### ISSUE TITLE
Добавление ескольких датчиков

### ISSUE THREAD

**Issue by kirillec** [Limych/ha-narodmon#120]
Здравствуйте!
Подскажите имеется ли возможность добавить сразу несколько датчиков в округе?
Я люблю народный мониторинг за то что можно просматривать температуру в разных районах города. Очень удобно когда на сайте или в приложении ты видишь сразу несколько датчиков температуры. А вот как можно добавить несколько датчиков температуры в HA. По умолчанию добавляется только один датчик температуры, который находиться ближе всего к моему местоположению...
Может как вариант можно было бы указать количество ближайших добавляемых датчиков?

**Comment by ruvasik** [comment]
https://github.com/Limych/ha-narodmon/issues/115

**Comment by kirillec** [comment]
> #115

Круто, здорово, вижу что люди уже год просят добавить эту возможность!
А реализация то где!?)

**Comment by skadiexe** [comment]
ну вроде бы ничего не мешает добавить в конфиг несколько штук devices и указать у них разные координаты

**Comment by kirillec** [comment]
> ну вроде бы ничего не мешает добавить в конфиг несколько штук devices и указать у них разные координаты

Если б ничего не мешало, не просили бы...
При добавление 2, 3 и более датчиков, работает всегда один, причём всегда рандомно..., остальные отваливаются!
