### ISSUE TITLE
Ошибка при рестарте интеграции

### ISSUE THREAD

**Issue by ASergeyV** [Limych/ha-narodmon#130]
### System Health details

Регистратор: homeassistant.config_entries
Источник: config_entries.py:772
Первое сообщение: 09:34:54 (1 сообщений)
Последнее сообщение: 09:34:54

Error unloading entry Home Assistant for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 772, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 140, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-narodmon/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

При рестарте интеграции в журнал HA (Core 2024.5.3) падает ошибка, сенсоры не добавляются. Хотелось бы узнать что не так?
configuration.yaml:
narodmon:
  devices:
    - name: "Narodmon"
      search_area_radius: 20
      latitude: 61.78
      longitude: 50.74

### Reproduction steps

1. Установка интеграции
2. Прописал в конфиг
3. Рестарт HA
4. Рестарт интеграции

### Debug logs

```text
.
```

**Comment by Valen13776** [comment]
Та же история (((

**Comment by sneakythr0ws** [comment]
+1

**Comment by sneakythr0ws** [comment]
Все еще не работает 2.2.0 (
