### ISSUE TITLE
Sensors are unavaibable.

### ISSUE THREAD

**Issue by sp0ok1** [Limych/ha-narodmon#144]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Asia/Yekaterinburg
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1452
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 28.6 GB
disk_used | 6.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Zigbee2MQTT (1.40.2-1), Terminal & SSH (9.15.0), NGINX Home Assistant SSL proxy (3.11.0), Duck DNS (1.18.0), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 16 октября 2024 г. в 04:46
-- | --
current_recorder_run | 26 октября 2024 г. в 07:47
estimated_db_size | 200.51 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-narodmon/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

After the last update of Core 2024.10.4, the sensors became unavailable.

### Reproduction steps

Cinfig YAML:
`narodmon:
  devices:
    - name: "Narodmon"
      sensors:
        - temperature
        - humidity
        - pressure`

### Debug logs

```text
There is no error data in the logs.
```

**Comment by Limych** [comment]
It's not a component bug.

**Comment by sof07** [comment]
> Это не ошибка компонента.

А можно по подробнее, в чем проблема? Я тоже с этим столкнулся.

**Comment by Limych** [comment]
> > Это не ошибка компонента.
> 
> А можно по подробнее, в чем проблема? Я тоже с этим столкнулся.

https://github.com/Limych/ha-narodmon?tab=readme-ov-file#known-limitations-and-issues

**Comment by sp0ok1** [comment]
> > Это не ошибка компонента.
> 
> А можно по подробнее, в чем проблема? Я тоже с этим столкнулся.

Даже на сайте проекта датчики не отображались.  Попробовал увеличить радиус до 25 км. Это тоже не помогло. Спустя сутки примерно все заработало.

**Comment by sof07** [comment]
> > > Это не ошибка компонента.
> > 
> > 
> > А можно подробнее, в чем проблема? Я тоже с этим столкнулся.
> 
> [https://github.com/Limych/ha-narodmon?tab=readme-ov-file#известные ограничения и проблемы](https://github.com/Limych/ha-narodmon?tab=readme-ov-file#known-limitations-and-issues)

Что я должен понять по ссылке?
Что можно настроить компонент только через конфиг? Настроил! Что Сервис Narodmon ограничивает объём данных, возвращаемых за один запрос и нужно время для обновления датчиков? Во-первых кроме update.narodmon_cloud_integration_update не появилось больше ничего, во вторых интеграция установлена и настроена по ссылке выше более месяца назад, за это время могли подтянуться датчики?

**Comment by Limych** [comment]
> > > > Это не ошибка компонента.
> > > 
> > > 
> > > А можно подробнее, в чем проблема? Я тоже с этим столкнулся.
> > 
> > 
> > [https://github.com/Limych/ha-narodmon?tab=readme-ov-file#известные ограничения и проблемы](https://github.com/Limych/ha-narodmon?tab=readme-ov-file#known-limitations-and-issues)
> 
> Что я должен понять по ссылке? Что можно настроить компонент только через конфиг? Настроил! Что Сервис Narodmon ограничивает объём данных, возвращаемых за один запрос и нужно время для обновления датчиков? Во-первых кроме update.narodmon_cloud_integration_update не появилось больше ничего, во вторых интеграция установлена и настроена по ссылке выше более месяца назад, за это время могли подтянуться датчики?

Если они не подтянулись и нет ошибок в логах, то либо в заданной области просто нет нужных датчиков, либо ошибка в работе API сайта.

**Comment by sof07** [comment]
> > > > > Это не ошибка компонента.
> > > > 
> > > > 
> > > > А можно подробнее, в чем проблема? Я тоже с этим столкнулся.
> > > 
> > > 
> > > [https://github.com/Limych/ha-narodmon?tab=readme-ov-file#известные ограничения и проблемы](https://github.com/Limych/ha-narodmon?tab=readme-ov-file#known-limitations-and-issues)
> > 
> > 
> > Что я должен понять из ссылки? Что компонент можно настроить только через конфиг? Настроил! Что сервис Narodmon ограничивает объём данных, возвращаемых за один запрос, и нужно время для обновления датчиков? Во-первых, кроме update.narodmon_cloud_integration_update больше ничего не появилось, во-вторых, интеграция была установлена и настроена по ссылке выше более месяца назад, за это время могли подтянуться датчики?
> 
> Если они не подтянулись и в логах нет ошибок, то либо в заданной области просто нет нужных датчиков, либо ошибка в работе API сайта.




Вернусь к вопросу, в логах кроме текста ниже ничего нет, радиус обнаружения поставил 50 км, хотя ближайший датчик находится в двух км от меня, ошибка в АПИ сайта? Но я так понял у других то работает...
```
2024-11-04 14:37:05.998 INFO (MainThread) [homeassistant.setup] Setting up narodmon
2024-11-04 14:37:06.000 INFO (MainThread) [homeassistant.setup] Setup of domain narodmon took 0.00 seconds
2024-11-04 14:37:06.000 INFO (MainThread) [custom_components.narodmon] 
-------------------------------------------------------------------
Narodmon Cloud Integration
Version: 2.2.1
This is a custom integration!
If you have ANY issues with this you need to open an issue here:
https://github.com/Limych/ha-narodmon/issues
```
вот мой конфиг, может в нем что то намудрил?

```
narodmon:
  devices:
    - name: "Narodmon"
      
      search_area_radius: 50
      sensors:
        - temperature
        - humidity
        - pressure
        - wind_speed
        - wind_bearing
        - precipitation
        - illuminance
        - radiation
        - uv
        - pm
```
