### ISSUE TITLE
Не работает интеграция

### ISSUE THREAD

**Issue by sof07** [Limych/ha-narodmon#145]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Moscow
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1522
Downloaded Repositories | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 93.8 GB
disk_used | 17.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), ESPHome (2024.10.2), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.1), Samba share (12.3.2), Tor (5.0.1), Zigbee2MQTT (1.40.2-1), Advanced SSH & Web Terminal (19.0.0), Studio Code Server (5.17.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 37
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23 октября 2024 г. в 09:04
-- | --
current_recorder_run | 23 октября 2024 г. в 12:04
estimated_db_size | 5444.34 MiB
database_engine | mysql
database_version | 11.2.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-narodmon/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Установил через HACS, в confirurations.yaml прописал следующие настройки
```
narodmon:
  devices:
    - name: "Narodmon"
      latitude: 55.659942
      longitude: 37.205111
      sensors:
        - temperature
        - humidity
        - pressure
        - wind_speed
        - wind_bearing
        - precipitation
        - illuminance
        - radiation
        - uv
        - pm
```
А датчиков нет
единственное, что вижу в панели разработчика
```
<html>
<body>
<!--StartFragment-->
update.narodmon_cloud_integration_updateNarodmon Cloud Integration update | off | auto_update: false installed_version: 2.2.0 in_progress: false latest_version: 2.2.0 release_summary: null release_url: https://github.com/Limych/ha-narodmon/releases/2.2.0 skipped_version: null title: null entity_picture: https://brands.home-assistant.io/_/narodmon/icon.png friendly_name: Narodmon Cloud Integration update supported_features: 23
-- | -- | --


<!--EndFragment-->
</body>
</html>[update.narodmon_cloud_integration_update](http://192.168.1.59:8123/developer-tools/state#)
Narodmon Cloud Integration update
off	auto_update: false
installed_version: 2.2.0
in_progress: false
latest_version: 2.2.0
release_summary: null
release_url: https://github.com/Limych/ha-narodmon/releases/2.2.0
skipped_version: null
title: null
entity_picture: https://brands.home-assistant.io/_/narodmon/icon.png
friendly_name: Narodmon Cloud Integration update
supported_features: 23
```

### Reproduction steps

1.Установил через HACS
2.Перезагрузил
3.Проверил состояния сенсоров
...

### Debug logs

```text
No
```

**Comment by Limych** [comment]
Компонент проверен на тестовой сборке на Ваших конфигах и всё работает нормально — потому и не было никаких ошибок.

Документация написана для того, чтобы её читать: https://github.com/Limych/ha-narodmon?tab=readme-ov-file#known-limitations-and-issues
