### ISSUE TITLE
Электроэнергия

### ISSUE THREAD

**Issue by semen-semenwc** [Limych/ha-narodmon#32]
У меня есть датчики: напряжения, тока, мощности, энергии. Возможно их вывести в вашей интеграции?

**Comment by Limych** [comment]
В данный момент компонент рассчитан на автоматический поиск географически ближайших общеупотребимых сенсоров. Перечисленные Вами датчики имеют смысл только для вас. Даже Вашему соседу, живущему (условно) в паре метров, они уже уже бесполезны. Потому, увы, сейчас такие сенсоры добавить не возможно.

Я подумаю, что можно придумать для таких случаев, как Ваш.
