### ISSUE TITLE
Integration doesn't work after 1.1.2 update

### ISSUE THREAD

**Issue by tarasifua** [Limych/ha-narodmon#56]
**Environment**

- Home Assistant Core release with the issue: 2021.12.8
- This custom component release with the issue: 1.1.2
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Supervisor

**Describe the bug**
Hi! At version 1.1.1 I had make a fix manually from pull request to make it work. At version 1.1.2, seems, that pull request was accepted, but integration doesn't work. I had enabled debug logging for it, and I can see in logs, that it received data for sensors correctly from api, but all my narodmon sensors have status "unknown" and don't shoe any data...

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by tarasifua** [comment]
Ok, I don't know why it was broken, but the problem is in sensor.py file. I had used old version of file and now it works perfect. As temporary fix just replace your file custom_components/narodmon/sensor.py with attached and it will work. Hope for fix soon, @Limych. Thank you for your work.
[sensor.py.zip](https://github.com/Limych/ha-narodmon/files/7841787/sensor.py.zip)

**Comment by EDV64** [comment]
Same issue. Temporary fix of **tarasifua** is working, thanks. Awaiting of integration fix

**Comment by chipmoca** [comment]
> В качестве временного исправления просто замените ваш файл
Спасибо! Это помогло мне, тоже была проблема. Два дня пытался решить ее ).

**Comment by Limych** [comment]
Fixed at version 1.1.3
