### ISSUE TITLE
Не стартует ha-narodmon 2.0.1

### ISSUE THREAD

**Issue by yarodin** [Limych/ha-narodmon#75]
**Environment**

- Home Assistant Core release with the issue: 2022.4.0
- This custom component release with the issue: 2.0.1
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Docker | 20.10.12

**Describe the bug**

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:663
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 09:26:00 (2 occurrences)
Last logged: 09:26:06

The system cannot restart because the configuration is not valid: Component error: narodmon - cannot import name 'T' from 'homeassistant.helpers.update_coordinator' (/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py)

**Configuration.yaml**
```yaml

configuration.yaml
narodmon: !include includes/custom/narodmon.yaml

narodmon.yaml
  apikey: myverysecretapikey
  devices:
    - name: Narodmon
      latitude: !secret latitude_coord
      longitude: !secret longitude_coord 
      scan_interval: '00:05'
      sensors:
        - temperature
        - humidity
        - pressure
        - precipitation
        - wind_speed
        - wind_bearing

**Comment by chernyde** [comment]
Still not working

**Comment by suarezcp87** [comment]
not working
