### ISSUE TITLE
Not start in HA 2022.4.1

### ISSUE THREAD

**Issue by vasyna** [Limych/ha-narodmon#76]
Good afternoon. Can't run integration. Installed using HACS, there is a directory with contents along the path
/config/custom_components/narodmon

When I add to the configuration:
narodmon:
devices:
- name: "Narodmon"
sensors:
- temperature
- pressure
I get an error:
Component error: narodmon - No module named 'custom_components.narodmon.api'

**Comment by Limych** [comment]
See #75
