### ISSUE TITLE
Ошибка при добавлении датчика и перезапуске HA

### ISSUE THREAD

**Issue by serviceiotcc** [Limych/ha-narodmon#80]
**Environment**

- Home Assistant Core release with the issue: core-2022.5.0
- This custom component release with the issue: 2.0.1
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Supervisor

**Describe the bug**

После скачивания компонента из HACS и ребута ХА, добавил в конфиг датчик, но HA ругается при перезагрузке:
![image](https://user-images.githubusercontent.com/74203855/167146919-d8aa4cc6-80da-4285-b4bd-8d98415c5ebf.png)

**Configuration.yaml**
```yaml

Add your configs here if any.

```

![image](https://user-images.githubusercontent.com/74203855/167147003-d44a1edd-65d1-4f48-a70f-41cf0bb93e0c.png)

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
Please update component to latest version.
