### ISSUE TITLE
Ошибка при добавлении датчика и перезапуске HA

### ISSUE THREAD

**Issue by serviceiotcc** [Limych/ha-narodmon#81]
**Environment**

- Home Assistant Core release with the issue: core-2021.5.5
- This custom component release with the issue: 2.0.2
- Last working this custom component release (if known): -
- Operating environment (Home Assistant/Supervisor/Docker/venv): Supervisor

**Describe the bug**
После скачивания компонента из HACS и ребута ХА, добавил в конфиг датчик, но HA ругается при перезагрузке:

![image](https://user-images.githubusercontent.com/74203855/168266622-5d92dd96-4879-4a25-89e9-4ccb642b42d8.png)

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
Обновите, пожалуйста, Home Assistant до свежей версии.
